### ISSUE TITLE
Initialise Testing

### ISSUE THREAD

**Issue by VictorAZ12** [VictorAZ12/web-request-forum#16]
It is required to implement testing. Initialisation of testing needs to be implemented.

**Comment by 22321855** [comment]
@VictorAZ12  I'm learning to use Selenium for front-end testing.

**Comment by 23882972** [comment]
I will import blueprint from flask to do the backend testing

**Comment by 22321855** [comment]
I have created 2 Selenium file to test Dashboard and Homepage.

**Comment by VictorAZ12** [comment]
Testing developing by Hung and Nikhil
