### ISSUE TITLE
HabitNest Home Page

### ISSUE THREAD

**Issue by Jackieljq** [VictorAZ12/web-request-forum#23]
**Files:**
index.html
HabitNest.css

**Details:**
index.html:
Navigation bar with links: Home, Habits, Challenges, Community, Login
Welcome section: Title, description, divider
Login/Register section:
Login form: Username, password, login button
Register form (hidden by default): Username, password, register button
Forgot Password link
Footer with site name

HabitNest.css:
General Styles: Background color
Navigation Bar: Background color, logo and link styles
Main Content: Padding, text alignment
Login/Register Section: Card styles, header and button styles
Footer: Background color, text alignment

**Comment by 22321855** [comment]
The homepage look great @Jackieljq. Just ensure you keep the reference for external image you used as teacher required. Thanks

**Comment by 22321855** [comment]
Also as mentioned in the previous team meeting, you may want to modify the current Team page.

**Comment by Jackieljq** [comment]
I have completed the update. Thank you for your suggestion.
