### ISSUE TITLE
Improved Login/Register Section with JavaScript

### ISSUE THREAD

**Issue by Jackieljq** [VictorAZ12/web-request-forum#25]
Added a new JavaScript file HabitNest.js to handle the login and register functionality.

**Comment by VictorAZ12** [comment]
Should be handled using WTForms tokens to avoid CRSF attacks, as required in lecture slides.

**Comment by VictorAZ12** [comment]
Submission handled by Flask WTForm. Need client-side validation, and display of error messages such as display "email registered"

**Comment by Jackieljq** [comment]
@VictorAZ12 I have added a simple demo of login error message to address basic validation on the client side. The form now displays messages for "user not registered" and "incorrect password".
<img width="500" alt="test2" src="https://github.com/VictorAZ12/web-request-forum/assets/165802357/afc4955e-d0be-475a-a4b9-d63ed8795854">
<img width="500" alt="testerror" src="https://github.com/VictorAZ12/web-request-forum/assets/165802357/bf67b431-358a-4724-9f79-483a468382ad">

**Comment by VictorAZ12** [comment]
Moved to #41
