### ISSUE TITLE
Improve UI/UX and add comment for HabitNest

### ISSUE THREAD

**Issue by Jackieljq** [VictorAZ12/web-request-forum#27]
Enhance the user interface and user experience of the HabitNest project.
**HTML:**
Ensured all elements have unique IDs and class names for better targeting and reduced conflicts.
Add comment to each section.

**CSS:**
Improve navigation bar styling, including dropdown menus, to enhance usability and appearance.
Standardize section paddings and margins to create a more cohesive layout and better spacing.
Detailed login/register section styling to provide a consistent and user-friendly experience.
Add comment to each section.

**JavaScript:**
Aim to create a more polished, user-friendly, and maintainable application that enhances the overall experience for users and developers alike.experience of the HabitNest project.
Add comment to each section.

**Comment by 22321855** [comment]
@Jackieljq  Hi, as we discussed, there are few app name errors that need to be fixed. 
Also I saw some icon/image have not been linked yet, so you may want to check about that. 
![image](https://github.com/VictorAZ12/web-request-forum/assets/141614036/79b976a1-a884-4e22-a7c3-2bb97e0cb80d)

**Comment by Jackieljq** [comment]
Completed it.
