### ISSUE TITLE
Update dashboard HTML with Jinja2 and Flask-WTF forms

### ISSUE THREAD

**Issue by 22321855** [VictorAZ12/web-request-forum#35]
Integrated front-end with Flask-WTF for secure form handling and server-side rendering.
Updated HTML templates to use Jinja2 and Flask-WTF forms.
Added CSRF protection to AJAX requests.
Modified JavaScript files to include CSRF tokens in requests and handle form submissions appropriately.

**Comment by VictorAZ12** [comment]
This issue is being tracked in #37. Please follow the progress there.
