### ISSUE TITLE
Implement Redirection to Dashboard After Login and Registration

### ISSUE THREAD

**Issue by Jackieljq** [VictorAZ12/web-request-forum#36]
This issue aims to implement the redirection to the dashboard page (Dashboard.html) after successful login or registration.

Update Login and Register Forms:
Add action attributes to the login and register forms in HabitNest.html to point to Dashboard.html.

Modify JavaScript for Redirection:
Update HabitNest.js to include event listeners for form submissions.
Ensure that after form validation, users are redirected to Dashboard.html.

Acceptance Criteria:
 After submitting the login form, users are redirected to the dashboard page.
 After submitting the registration form, users are redirected to the dashboard page.
 The paths to Dashboard.html are correctly configured and accessible.

**Comment by Jackieljq** [comment]
@22321855 I've noticed that the Dashboard page does not correctly link to the CSS files, I hope you can make these changes. Thank you!

**Comment by VictorAZ12** [comment]
That's a redirect returned from server. I can implement that from backend.

**Comment by VictorAZ12** [comment]
Already done
