### ISSUE TITLE
habit/challenge loading JS functions

### ISSUE THREAD

**Issue by VictorAZ12** [VictorAZ12/web-request-forum#40]
The loading of habits/challenges is trying to retrieve some attributes that do not existing in current Habit/Challenge models. Changes need to be made in HTML and Javascript files of dashboard. API documentation is provided for retrieving.

**Comment by 22321855** [comment]
Thanks @VictorAZ12, as we discussed I will modify it accordingly.

**Comment by VictorAZ12** [comment]
Fixed already.
