### ISSUE TITLE
Form submission response handling

### ISSUE THREAD

**Issue by VictorAZ12** [VictorAZ12/web-request-forum#41]
After we submit a CSRF protected form, our webapp should receive a response from the server, then determine if the user should see an error message, a success message, or be redirected to another page.
Current form submission is basic and can be improved with custom Javascript to submit form to server and handle response accordingly.

**Comment by VictorAZ12** [comment]
Login and registration part: see issue #36

**Comment by Jackieljq** [comment]
We tested it successfully yesterday. Thanks for your effort!
