### ISSUE TITLE
User Dashboard Issues

### ISSUE THREAD

**Issue by 22321855** [VictorAZ12/web-request-forum#56]
![image](https://github.com/VictorAZ12/web-request-forum/assets/141614036/d25acbe6-df20-4e2e-a9cd-3412d14f03a4)
![image](https://github.com/VictorAZ12/web-request-forum/assets/141614036/d64b875f-0ee6-4fd2-a1f9-550c1ccf800a)
![image](https://github.com/VictorAZ12/web-request-forum/assets/141614036/1426c6a7-6389-413d-abaf-6305e462bdd0)

The current Dashboard been able to load the profile_image and to get the correct user.username from the database. 
The new habit form can get habit_type from the database. 

There are some issues, after user input all the required information and click save, nothing happen, it seems to be issue with API as well. 
Also in create challenges, it does not load base_habit.

**Comment by VictorAZ12** [comment]
thanks for the feedback, will look into the issues later

**Comment by VictorAZ12** [comment]
Resolved
